name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and analyze StorageScope with xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -scheme StorageScope -destination 'platform=macOS' build analyze CODE_SIGNING_ALLOWED=NO
